name: CI/CD - Lambda + FastAPI + Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Descargar el repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Configurar Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3️⃣ Crear y activar virtualenv + instalar dependencias
    - name: Setup virtualenv and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install zappa

    # 4️⃣ Ejecutar TODAS las pruebas unitarias (Lambda + DB + FastAPI)
    - name: Run all tests
      run: |
        source venv/bin/activate
        pytest tests/ --maxfail=1 --disable-warnings -q

    # 5️⃣ Desplegar Lambda con Zappa
    - name: Deploy Lambda with Zappa
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        source venv/bin/activate
        zappa update dev
        zappa update processor

    # 6️⃣ Copiar el código FastAPI a la EC2
    - name: Copy FastAPI code to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "fastapi/*"
        target: "/home/ubuntu/ProjectoDolar/fastapi"

    # 7️⃣ Instalar dependencias de FastAPI + reiniciar el servicio en la EC2
    - name: Restart FastAPI service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/ProjectoDolar/fastapi
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          sudo systemctl restart fastapi.service
