name: Zappa Deploy

on:
  push:
    branches:
      - main  # o la rama que uses para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # opcional si usas credenciales temporales
      AWS_DEFAULT_REGION: us-east-1  # tu región
      AWS_PROFILE: ""  # IMPORTANTE: vacío para que Zappa no busque default

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install zappa

      - name: Zappa Update
        run: |
          source venv/bin/activate
          # Forzar a Zappa a ignorar profile usando la opción --aws-profile ""
          zappa update dev --aws-profile ""
