name: CI/CD - Lambda Tests + Zappa Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar el repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install zappa

      # 4️⃣ Ejecutar tests de Lambda
      - name: Run Lambda tests
        run: pytest --maxfail=1 --disable-warnings -q

      # 5️⃣ Desplegar Lambda con Zappa usando variables de entorno
      - name: Deploy Lambda with Zappa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          # Importante: NO definir AWS_PROFILE
          zappa update dev
